# Generated by Django 3.0.2 on 2020-02-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCodes',
            fields=[
                ('companyID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Company Codes',
            },
        ),
        migrations.CreateModel(
            name='ProductSellers',
            fields=[
                ('product', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CompanyCodes')),
            ],
            options={
                'verbose_name_plural': 'Product Sellers',
            },
        ),
        migrations.CreateModel(
            name='DerivativeTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeID', models.CharField(max_length=30)),
                ('dateOfTrade', models.DateTimeField()),
                ('product', models.CharField(max_length=30)),
                ('notionalAmount', models.DecimalField(decimal_places=6, max_digits=20)),
                ('notionalCurrency', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('maturityDate', models.DateField()),
                ('underlyingPrice', models.DecimalField(decimal_places=6, max_digits=20)),
                ('underlyingCurrency', models.CharField(max_length=30)),
                ('strikePrice', models.DecimalField(decimal_places=6, max_digits=20)),
                ('archived', models.BooleanField(default=True)),
                ('buyingParty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyingParty_CompanyCode', to='application.CompanyCodes')),
                ('sellingParty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellingParty_CompanyCode', to='application.CompanyCodes')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', models.CharField(max_length=30)),
                ('valueInUSD', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Currency Values',
                'unique_together': {('date', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='StockPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stockPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('companyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CompanyCodes')),
            ],
            options={
                'verbose_name_plural': 'Stock Prices',
                'unique_together': {('date', 'companyID')},
            },
        ),
        migrations.CreateModel(
            name='ProductPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marketPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.ProductSellers')),
            ],
            options={
                'verbose_name_plural': 'Product Prices',
                'unique_together': {('date', 'product')},
            },
        ),
    ]
