# Generated by Django 3.0.2 on 2020-02-04 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('currency', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AlterField(
            model_name='derivativetrades',
            name='notionalCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notionalCurrency_Currencies', to='application.CompanyCodes'),
        ),
        migrations.AlterField(
            model_name='derivativetrades',
            name='underlyingCurrency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='underlyingCurrency_Currencies', to='application.CompanyCodes'),
        ),
        migrations.AlterField(
            model_name='currencyvalues',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Currencies'),
        ),
    ]
