# Generated by Django 2.0.7 on 2020-02-04 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200204_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='derivativetrades',
            options={'verbose_name_plural': 'Derivative Trades'},
        ),
    ]
