# Generated by Django 3.0.3 on 2020-02-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200204_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivativetrades',
            name='tradeID',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
